# Generated by Django 4.2.2 on 2023-06-29 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simpconnect_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
