# Generated by Django 4.2.2 on 2023-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simpconnect_api", "0002_customuser_liked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
